parameters:

    #
    # Parameters
    #
    gearman.cache.id:               gearman.workers

    #
    # Generators
    #
    gearman.unique_job_identifier.class: Mmoreram\GearmanBundle\Generator\UniqueJobIdentifierGenerator

    #
    # Dispatchers
    #
    gearman.dispatcher.callbacks.class: Mmoreram\GearmanBundle\Dispatcher\GearmanCallbacksDispatcher

    #
    # Services
    #
    gearman.client.class:           Mmoreram\GearmanBundle\Service\GearmanClient
    gearman.callbacks.class:        Mmoreram\GearmanBundle\Service\GearmanCallbacks
    gearman.execute.class:          Mmoreram\GearmanBundle\Service\GearmanExecute
    gearman.describer.class:        Mmoreram\GearmanBundle\Service\GearmanDescriber
    gearman.parser.class:           Mmoreram\GearmanBundle\Service\GearmanParser
    gearman.cache.wrapper.class:    Mmoreram\GearmanBundle\Service\GearmanCacheWrapper

    #
    # External
    #
    gearman.external.finder.class:  Symfony\Component\Finder\Finder
